version: '2.2'
services:
  rabbit:
    image: "rabbitmq"
    restart: always
    ports:
      - "5672:5672"
  consumer:
    build:
      context: .
      dockerfile: ConsumerDockerfile
    restart: always
    depends_on:
      - rabbit
  producer:
    build:
      context: .
      dockerfile: ProducerDockerfile
    restart: always
    depends_on:
      - rabbit
